version: '3.8'

services:

  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: redlink-local-db
    ports:
      - "5431:5432"
    volumes:
      - redlink-db-data:/var/lib/postgresql/data/

volumes:
  redlink-db-data:
