//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Application.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string EnterProductName {
            get {
                return ResourceManager.GetString("EnterProductName", resourceCulture);
            }
        }
        
        internal static string AttachProductPhoto {
            get {
                return ResourceManager.GetString("AttachProductPhoto", resourceCulture);
            }
        }
        
        internal static string ChooseProductCondition {
            get {
                return ResourceManager.GetString("ChooseProductCondition", resourceCulture);
            }
        }
        
        internal static string EnterProductPrice {
            get {
                return ResourceManager.GetString("EnterProductPrice", resourceCulture);
            }
        }
        
        internal static string ChooseLanguageFromList {
            get {
                return ResourceManager.GetString("ChooseLanguageFromList", resourceCulture);
            }
        }
        
        internal static string SelectedCountry {
            get {
                return ResourceManager.GetString("SelectedCountry", resourceCulture);
            }
        }
        
        internal static string SelectedLanguage {
            get {
                return ResourceManager.GetString("SelectedLanguage", resourceCulture);
            }
        }
        
        internal static string TypeMsgForProductNameErr {
            get {
                return ResourceManager.GetString("TypeMsgForProductNameErr", resourceCulture);
            }
        }
        
        internal static string ProductNameAtLeast5CharsErr {
            get {
                return ResourceManager.GetString("ProductNameAtLeast5CharsErr", resourceCulture);
            }
        }
        
        internal static string AttachPhotoErr {
            get {
                return ResourceManager.GetString("AttachPhotoErr", resourceCulture);
            }
        }
        
        internal static string UseMenuForProductConditonErr {
            get {
                return ResourceManager.GetString("UseMenuForProductConditonErr", resourceCulture);
            }
        }
        
        internal static string TypeMsgForProductPriceErr {
            get {
                return ResourceManager.GetString("TypeMsgForProductPriceErr", resourceCulture);
            }
        }
        
        internal static string IncorrectProductPriceFormatErr {
            get {
                return ResourceManager.GetString("IncorrectProductPriceFormatErr", resourceCulture);
            }
        }
        
        internal static string ProductPriceGtr0Err {
            get {
                return ResourceManager.GetString("ProductPriceGtr0Err", resourceCulture);
            }
        }
        
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        internal static string ChangeCountry {
            get {
                return ResourceManager.GetString("ChangeCountry", resourceCulture);
            }
        }
        
        internal static string ChooseCountryFromList {
            get {
                return ResourceManager.GetString("ChooseCountryFromList", resourceCulture);
            }
        }
        
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        internal static string ICanHelpToSellClothes {
            get {
                return ResourceManager.GetString("ICanHelpToSellClothes", resourceCulture);
            }
        }
        
        internal static string YouCanUseMeUsingCommands {
            get {
                return ResourceManager.GetString("YouCanUseMeUsingCommands", resourceCulture);
            }
        }
        
        internal static string CountryHelpsProvideRelevantProducts {
            get {
                return ResourceManager.GetString("CountryHelpsProvideRelevantProducts", resourceCulture);
            }
        }
        
        internal static string YourCurrProfileSettings {
            get {
                return ResourceManager.GetString("YourCurrProfileSettings", resourceCulture);
            }
        }
        
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        internal static string UseBtnsToChangeProfile {
            get {
                return ResourceManager.GetString("UseBtnsToChangeProfile", resourceCulture);
            }
        }
        
        internal static string TheProductYouCreated {
            get {
                return ResourceManager.GetString("TheProductYouCreated", resourceCulture);
            }
        }
        
        internal static string ReviewProductInformation {
            get {
                return ResourceManager.GetString("ReviewProductInformation", resourceCulture);
            }
        }
        
        internal static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        internal static string USA {
            get {
                return ResourceManager.GetString("USA", resourceCulture);
            }
        }
        
        internal static string Ukraine {
            get {
                return ResourceManager.GetString("Ukraine", resourceCulture);
            }
        }
        
        internal static string Poland {
            get {
                return ResourceManager.GetString("Poland", resourceCulture);
            }
        }
        
        internal static string Russia {
            get {
                return ResourceManager.GetString("Russia", resourceCulture);
            }
        }
        
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        internal static string Ukrainian {
            get {
                return ResourceManager.GetString("Ukrainian", resourceCulture);
            }
        }
        
        internal static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        internal static string Perfect {
            get {
                return ResourceManager.GetString("Perfect", resourceCulture);
            }
        }
        
        internal static string VeryGood {
            get {
                return ResourceManager.GetString("VeryGood", resourceCulture);
            }
        }
        
        internal static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        internal static string Satisfactory {
            get {
                return ResourceManager.GetString("Satisfactory", resourceCulture);
            }
        }
        
        internal static string Clothes {
            get {
                return ResourceManager.GetString("Clothes", resourceCulture);
            }
        }
        
        internal static string Outerwear {
            get {
                return ResourceManager.GetString("Outerwear", resourceCulture);
            }
        }
        
        internal static string Lingerie {
            get {
                return ResourceManager.GetString("Lingerie", resourceCulture);
            }
        }
        
        internal static string Footwear {
            get {
                return ResourceManager.GetString("Footwear", resourceCulture);
            }
        }
        
        internal static string Bags {
            get {
                return ResourceManager.GetString("Bags", resourceCulture);
            }
        }
        
        internal static string Accessories {
            get {
                return ResourceManager.GetString("Accessories", resourceCulture);
            }
        }
        
        internal static string Jewelry {
            get {
                return ResourceManager.GetString("Jewelry", resourceCulture);
            }
        }
        
        internal static string ClothesForHome {
            get {
                return ResourceManager.GetString("ClothesForHome", resourceCulture);
            }
        }
        
        internal static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        internal static string Seller {
            get {
                return ResourceManager.GetString("Seller", resourceCulture);
            }
        }
        
        internal static string SelectedCondition {
            get {
                return ResourceManager.GetString("SelectedCondition", resourceCulture);
            }
        }
        
        internal static string UseMenuForProductCurrencyErr {
            get {
                return ResourceManager.GetString("UseMenuForProductCurrencyErr", resourceCulture);
            }
        }
        
        internal static string ChooseProductCurrency {
            get {
                return ResourceManager.GetString("ChooseProductCurrency", resourceCulture);
            }
        }
        
        internal static string PublishPostErr {
            get {
                return ResourceManager.GetString("PublishPostErr", resourceCulture);
            }
        }
        
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        internal static string ChooseProductCategory {
            get {
                return ResourceManager.GetString("ChooseProductCategory", resourceCulture);
            }
        }
        
        internal static string ChooseProductSection {
            get {
                return ResourceManager.GetString("ChooseProductSection", resourceCulture);
            }
        }
        
        internal static string ChosenCategory {
            get {
                return ResourceManager.GetString("ChosenCategory", resourceCulture);
            }
        }
        
        internal static string ChosenCondition {
            get {
                return ResourceManager.GetString("ChosenCondition", resourceCulture);
            }
        }
        
        internal static string ChosenCurrency {
            get {
                return ResourceManager.GetString("ChosenCurrency", resourceCulture);
            }
        }
        
        internal static string AnkleBoots {
            get {
                return ResourceManager.GetString("AnkleBoots", resourceCulture);
            }
        }
        
        internal static string Boots {
            get {
                return ResourceManager.GetString("Boots", resourceCulture);
            }
        }
        
        internal static string Sneakers {
            get {
                return ResourceManager.GetString("Sneakers", resourceCulture);
            }
        }
        
        internal static string Uggs {
            get {
                return ResourceManager.GetString("Uggs", resourceCulture);
            }
        }
        
        internal static string RubberisedBoots {
            get {
                return ResourceManager.GetString("RubberisedBoots", resourceCulture);
            }
        }
        
        internal static string FlipFlops {
            get {
                return ResourceManager.GetString("FlipFlops", resourceCulture);
            }
        }
        
        internal static string Shoes {
            get {
                return ResourceManager.GetString("Shoes", resourceCulture);
            }
        }
        
        internal static string Ballerinas {
            get {
                return ResourceManager.GetString("Ballerinas", resourceCulture);
            }
        }
        
        internal static string Loafers {
            get {
                return ResourceManager.GetString("Loafers", resourceCulture);
            }
        }
        
        internal static string Sandals {
            get {
                return ResourceManager.GetString("Sandals", resourceCulture);
            }
        }
        
        internal static string Moccasins {
            get {
                return ResourceManager.GetString("Moccasins", resourceCulture);
            }
        }
        
        internal static string Espadrilles {
            get {
                return ResourceManager.GetString("Espadrilles", resourceCulture);
            }
        }
        
        internal static string Slippers {
            get {
                return ResourceManager.GetString("Slippers", resourceCulture);
            }
        }
        
        internal static string Mules {
            get {
                return ResourceManager.GetString("Mules", resourceCulture);
            }
        }
        
        internal static string Backpacks {
            get {
                return ResourceManager.GetString("Backpacks", resourceCulture);
            }
        }
        
        internal static string ClutchBags {
            get {
                return ResourceManager.GetString("ClutchBags", resourceCulture);
            }
        }
        
        internal static string ToiletryBags {
            get {
                return ResourceManager.GetString("ToiletryBags", resourceCulture);
            }
        }
        
        internal static string DocumentCovers {
            get {
                return ResourceManager.GetString("DocumentCovers", resourceCulture);
            }
        }
        
        internal static string Cardholders {
            get {
                return ResourceManager.GetString("Cardholders", resourceCulture);
            }
        }
        
        internal static string Wallets {
            get {
                return ResourceManager.GetString("Wallets", resourceCulture);
            }
        }
        
        internal static string Knitwear {
            get {
                return ResourceManager.GetString("Knitwear", resourceCulture);
            }
        }
        
        internal static string SweatshirtsHoodies {
            get {
                return ResourceManager.GetString("SweatshirtsHoodies", resourceCulture);
            }
        }
        
        internal static string Trousers {
            get {
                return ResourceManager.GetString("Trousers", resourceCulture);
            }
        }
        
        internal static string TShirts {
            get {
                return ResourceManager.GetString("TShirts", resourceCulture);
            }
        }
        
        internal static string Shirts {
            get {
                return ResourceManager.GetString("Shirts", resourceCulture);
            }
        }
        
        internal static string Shorts {
            get {
                return ResourceManager.GetString("Shorts", resourceCulture);
            }
        }
        
        internal static string SuitsJumpsuits {
            get {
                return ResourceManager.GetString("SuitsJumpsuits", resourceCulture);
            }
        }
        
        internal static string Loungewear {
            get {
                return ResourceManager.GetString("Loungewear", resourceCulture);
            }
        }
        
        internal static string Sportswear {
            get {
                return ResourceManager.GetString("Sportswear", resourceCulture);
            }
        }
        
        internal static string Skirts {
            get {
                return ResourceManager.GetString("Skirts", resourceCulture);
            }
        }
        
        internal static string Jeans {
            get {
                return ResourceManager.GetString("Jeans", resourceCulture);
            }
        }
        
        internal static string Dresses {
            get {
                return ResourceManager.GetString("Dresses", resourceCulture);
            }
        }
        
        internal static string Coats {
            get {
                return ResourceManager.GetString("Coats", resourceCulture);
            }
        }
        
        internal static string TrenchCoats {
            get {
                return ResourceManager.GetString("TrenchCoats", resourceCulture);
            }
        }
        
        internal static string Jackets {
            get {
                return ResourceManager.GetString("Jackets", resourceCulture);
            }
        }
        
        internal static string FurCoats {
            get {
                return ResourceManager.GetString("FurCoats", resourceCulture);
            }
        }
        
        internal static string Gilets {
            get {
                return ResourceManager.GetString("Gilets", resourceCulture);
            }
        }
        
        internal static string Blazers {
            get {
                return ResourceManager.GetString("Blazers", resourceCulture);
            }
        }
        
        internal static string PufferJackets {
            get {
                return ResourceManager.GetString("PufferJackets", resourceCulture);
            }
        }
        
        internal static string Parkas {
            get {
                return ResourceManager.GetString("Parkas", resourceCulture);
            }
        }
        
        internal static string DoubleFacedJackets {
            get {
                return ResourceManager.GetString("DoubleFacedJackets", resourceCulture);
            }
        }
        
        internal static string Glasses {
            get {
                return ResourceManager.GetString("Glasses", resourceCulture);
            }
        }
        
        internal static string Headwear {
            get {
                return ResourceManager.GetString("Headwear", resourceCulture);
            }
        }
        
        internal static string Headwears {
            get {
                return ResourceManager.GetString("Headwears", resourceCulture);
            }
        }
        
        internal static string Belts {
            get {
                return ResourceManager.GetString("Belts", resourceCulture);
            }
        }
        
        internal static string Scarves {
            get {
                return ResourceManager.GetString("Scarves", resourceCulture);
            }
        }
        
        internal static string Gloves {
            get {
                return ResourceManager.GetString("Gloves", resourceCulture);
            }
        }
        
        internal static string Umbrellas {
            get {
                return ResourceManager.GetString("Umbrellas", resourceCulture);
            }
        }
        
        internal static string Bras {
            get {
                return ResourceManager.GetString("Bras", resourceCulture);
            }
        }
        
        internal static string Briefs {
            get {
                return ResourceManager.GetString("Briefs", resourceCulture);
            }
        }
        
        internal static string Swimwear {
            get {
                return ResourceManager.GetString("Swimwear", resourceCulture);
            }
        }
        
        internal static string SocksTights {
            get {
                return ResourceManager.GetString("SocksTights", resourceCulture);
            }
        }
        
        internal static string Bodysuits {
            get {
                return ResourceManager.GetString("Bodysuits", resourceCulture);
            }
        }
        
        internal static string Corsets {
            get {
                return ResourceManager.GetString("Corsets", resourceCulture);
            }
        }
        
        internal static string Jewellery {
            get {
                return ResourceManager.GetString("Jewellery", resourceCulture);
            }
        }
        
        internal static string Necklaces {
            get {
                return ResourceManager.GetString("Necklaces", resourceCulture);
            }
        }
        
        internal static string Rings {
            get {
                return ResourceManager.GetString("Rings", resourceCulture);
            }
        }
        
        internal static string Bracelets {
            get {
                return ResourceManager.GetString("Bracelets", resourceCulture);
            }
        }
        
        internal static string LegBracelets {
            get {
                return ResourceManager.GetString("LegBracelets", resourceCulture);
            }
        }
        
        internal static string Earrings {
            get {
                return ResourceManager.GetString("Earrings", resourceCulture);
            }
        }
        
        internal static string EarCuffs {
            get {
                return ResourceManager.GetString("EarCuffs", resourceCulture);
            }
        }
        
        internal static string HairClips {
            get {
                return ResourceManager.GetString("HairClips", resourceCulture);
            }
        }
        
        internal static string Nightwear {
            get {
                return ResourceManager.GetString("Nightwear", resourceCulture);
            }
        }
        
        internal static string Pyjamas {
            get {
                return ResourceManager.GetString("Pyjamas", resourceCulture);
            }
        }
        
        internal static string SlipDresses {
            get {
                return ResourceManager.GetString("SlipDresses", resourceCulture);
            }
        }
        
        internal static string DressingGowns {
            get {
                return ResourceManager.GetString("DressingGowns", resourceCulture);
            }
        }
        
        internal static string Perfumes {
            get {
                return ResourceManager.GetString("Perfumes", resourceCulture);
            }
        }
        
        internal static string CosmeticsAndAccessories {
            get {
                return ResourceManager.GetString("CosmeticsAndAccessories", resourceCulture);
            }
        }
        
        internal static string DogsClothesAndAccessories {
            get {
                return ResourceManager.GetString("DogsClothesAndAccessories", resourceCulture);
            }
        }
        
        internal static string BudgetProduct {
            get {
                return ResourceManager.GetString("BudgetProduct", resourceCulture);
            }
        }
        
        internal static string ModerateProduct {
            get {
                return ResourceManager.GetString("ModerateProduct", resourceCulture);
            }
        }
        
        internal static string ExpensiveProduct {
            get {
                return ResourceManager.GetString("ExpensiveProduct", resourceCulture);
            }
        }
    }
}
