//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Application.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string EnterProductName {
            get {
                return ResourceManager.GetString("EnterProductName", resourceCulture);
            }
        }
        
        internal static string AttachProductPhoto {
            get {
                return ResourceManager.GetString("AttachProductPhoto", resourceCulture);
            }
        }
        
        internal static string ChooseProductCondition {
            get {
                return ResourceManager.GetString("ChooseProductCondition", resourceCulture);
            }
        }
        
        internal static string EnterProductPrice {
            get {
                return ResourceManager.GetString("EnterProductPrice", resourceCulture);
            }
        }
        
        internal static string ChooseLanguageFromList {
            get {
                return ResourceManager.GetString("ChooseLanguageFromList", resourceCulture);
            }
        }
        
        internal static string SelectedCountry {
            get {
                return ResourceManager.GetString("SelectedCountry", resourceCulture);
            }
        }
        
        internal static string SelectedLanguage {
            get {
                return ResourceManager.GetString("SelectedLanguage", resourceCulture);
            }
        }
        
        internal static string TypeMsgForProductNameErr {
            get {
                return ResourceManager.GetString("TypeMsgForProductNameErr", resourceCulture);
            }
        }
        
        internal static string ProductNameAtLeast5CharsErr {
            get {
                return ResourceManager.GetString("ProductNameAtLeast5CharsErr", resourceCulture);
            }
        }
        
        internal static string AttachPhotoErr {
            get {
                return ResourceManager.GetString("AttachPhotoErr", resourceCulture);
            }
        }
        
        internal static string UseMenuForProductConditonErr {
            get {
                return ResourceManager.GetString("UseMenuForProductConditonErr", resourceCulture);
            }
        }
        
        internal static string TypeMsgForProductPriceErr {
            get {
                return ResourceManager.GetString("TypeMsgForProductPriceErr", resourceCulture);
            }
        }
        
        internal static string IncorrectProductPriceFormatErr {
            get {
                return ResourceManager.GetString("IncorrectProductPriceFormatErr", resourceCulture);
            }
        }
        
        internal static string ProductPriceGtr0Err {
            get {
                return ResourceManager.GetString("ProductPriceGtr0Err", resourceCulture);
            }
        }
        
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        internal static string ChangeCountry {
            get {
                return ResourceManager.GetString("ChangeCountry", resourceCulture);
            }
        }
        
        internal static string ChooseCountryFromList {
            get {
                return ResourceManager.GetString("ChooseCountryFromList", resourceCulture);
            }
        }
        
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        internal static string ICanHelpToSellClothes {
            get {
                return ResourceManager.GetString("ICanHelpToSellClothes", resourceCulture);
            }
        }
        
        internal static string YouCanUseMeUsingCommands {
            get {
                return ResourceManager.GetString("YouCanUseMeUsingCommands", resourceCulture);
            }
        }
        
        internal static string CountryHelpsProvideRelevantProducts {
            get {
                return ResourceManager.GetString("CountryHelpsProvideRelevantProducts", resourceCulture);
            }
        }
        
        internal static string YourCurrProfileSettings {
            get {
                return ResourceManager.GetString("YourCurrProfileSettings", resourceCulture);
            }
        }
        
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        internal static string UseBtnsToChangeProfile {
            get {
                return ResourceManager.GetString("UseBtnsToChangeProfile", resourceCulture);
            }
        }
        
        internal static string TheProductYouCreated {
            get {
                return ResourceManager.GetString("TheProductYouCreated", resourceCulture);
            }
        }
        
        internal static string ReviewProductInformation {
            get {
                return ResourceManager.GetString("ReviewProductInformation", resourceCulture);
            }
        }
        
        internal static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        internal static string USA {
            get {
                return ResourceManager.GetString("USA", resourceCulture);
            }
        }
        
        internal static string Ukraine {
            get {
                return ResourceManager.GetString("Ukraine", resourceCulture);
            }
        }
        
        internal static string Poland {
            get {
                return ResourceManager.GetString("Poland", resourceCulture);
            }
        }
        
        internal static string Russia {
            get {
                return ResourceManager.GetString("Russia", resourceCulture);
            }
        }
        
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        internal static string Ukrainian {
            get {
                return ResourceManager.GetString("Ukrainian", resourceCulture);
            }
        }
        
        internal static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        internal static string Perfect {
            get {
                return ResourceManager.GetString("Perfect", resourceCulture);
            }
        }
        
        internal static string VeryGood {
            get {
                return ResourceManager.GetString("VeryGood", resourceCulture);
            }
        }
        
        internal static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        internal static string Satisfactory {
            get {
                return ResourceManager.GetString("Satisfactory", resourceCulture);
            }
        }
        
        internal static string Clothes {
            get {
                return ResourceManager.GetString("Clothes", resourceCulture);
            }
        }
        
        internal static string OuterWear {
            get {
                return ResourceManager.GetString("OuterWear", resourceCulture);
            }
        }
        
        internal static string Lingerie {
            get {
                return ResourceManager.GetString("Lingerie", resourceCulture);
            }
        }
        
        internal static string FootWear {
            get {
                return ResourceManager.GetString("FootWear", resourceCulture);
            }
        }
        
        internal static string Bags {
            get {
                return ResourceManager.GetString("Bags", resourceCulture);
            }
        }
        
        internal static string Accessories {
            get {
                return ResourceManager.GetString("Accessories", resourceCulture);
            }
        }
        
        internal static string Jewelry {
            get {
                return ResourceManager.GetString("Jewelry", resourceCulture);
            }
        }
        
        internal static string ClothesForHome {
            get {
                return ResourceManager.GetString("ClothesForHome", resourceCulture);
            }
        }
        
        internal static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        internal static string Seller {
            get {
                return ResourceManager.GetString("Seller", resourceCulture);
            }
        }
        
        internal static string SelectedCondition {
            get {
                return ResourceManager.GetString("SelectedCondition", resourceCulture);
            }
        }
    }
}
